language: php
php:
  - '5.6'

install:
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.travis.xml
  - vendor/bin/phpcs --standard=PSR2 lib/ src/ tests/ web/

after_success:
  - travis_retry php vendor/bin/coveralls
